---
- name: Record excluder state and disable
  hosts: l_oo_all_hosts
  gather_facts: no
  tasks:

  # During installation the excluders are installed with present state.
  # So no pre-validation check here as the excluders are either to be installed (present = latest)
  # or they are not going to be updated if already installed

  # disable excluders based on their status
  - include_role:
      name: openshift_excluder
      tasks_from: disable
    vars:
      openshift_excluder_package_state: present
      docker_excluder_package_state: present
