---
- set_fact: kibana_key={{ lookup('file', openshift_logging_kibana_key) | b64encode }}
  when: "{{ openshift_logging_kibana_key | trim | length > 0 }}"
  changed_when: false

- set_fact: kibana_cert={{ lookup('file', openshift_logging_kibana_cert)| b64encode  }}
  when: "{{openshift_logging_kibana_cert | trim | length > 0}}"
  changed_when: false

- set_fact: kibana_ca={{ lookup('file', openshift_logging_kibana_ca)| b64encode  }}
  when: "{{openshift_logging_kibana_ca | trim | length > 0}}"
  changed_when: false

- set_fact: kibana_ca={{key_pairs | entry_from_named_pair('ca_file') }}
  when: kibana_ca is not defined
  changed_when: false

- name: Generating logging routes
  template: src=route_reencrypt.j2 dest={{mktemp.stdout}}/templates/logging-{{route_info.name}}-route.yaml
  tags: routes
  vars:
    obj_name: "{{route_info.name}}"
    route_host: "{{route_info.host}}"
    service_name: "{{route_info.name}}"
    tls_key: "{{kibana_key | default('') | b64decode}}"
    tls_cert: "{{kibana_cert | default('') | b64decode}}"
    tls_ca_cert: "{{kibana_ca | b64decode}}"
    tls_dest_ca_cert: "{{key_pairs | entry_from_named_pair('ca_file')| b64decode }}"
    edge_term_policy: "{{openshift_logging_kibana_edge_term_policy | default('') }}"
    labels:
      component: support
      logging-infra: support
      provider: openshift
  with_items:
    - {name: logging-kibana, host: "{{openshift_logging_kibana_hostname}}"}
    - {name: logging-kibana-ops, host: "{{openshift_logging_kibana_ops_hostname}}"}
  loop_control:
    loop_var: route_info
  when: (route_info.name == 'logging-kibana-ops' and openshift_logging_use_ops | bool) or route_info.name == 'logging-kibana'
  changed_when: no
